# kubernetes/manifests/security-tools/github-runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gitops-runner
  namespace: security-tools
spec:
  replicas: 1
  template:
    spec:
      # Substitui pelo teu owner/repo do GitHub antes do kubectl apply
      repository: YOUR_GITHUB_USER/gitops-devsecops-aws
      labels:
        - self-hosted
        - paris
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"