serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${harbor_role_arn}"

externalURL: https://harbor.security.internal

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      size: 20Gi
    database:
      size: 5Gi
    redis:
      size: 1Gi

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"